version: '3.8'
services:
  wordpress:
    image: wordpress
    restart: always
    deploy:
      replicas: 3
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wp_network
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: rootpass
    networks:
      - wp_network
    volumes:
      - db:/var/lib/mysql



networks:
  wp_network:
    driver: bridge

    
volumes:
  wordpress:
  db: